version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    environment:
      - PREDICTION_SERVICE_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
