build:
  images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  options:
    logging: CLOUD_LOGGING_ONLY
    substitutionOption: ALLOW_LOOSE
  steps:
  - args:
    - build
    - --no-cache
    - -t
    - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    - .
    - -f
    - frontend.dockerfile
    id: Build
    name: gcr.io/cloud-builders/docker
  - args:
    - push
    - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
    name: gcr.io/cloud-builders/docker
  - args:
    - run
    - services
    - update
    - $_SERVICE_NAME
    - --platform=managed
    - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
    - --region=$_DEPLOY_REGION
    - --quiet
    entrypoint: gcloud
    id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  substitutions:
    _AR_HOSTNAME: asia-south2-docker.pkg.dev
    _DEPLOY_REGION: asia-south2
    _PLATFORM: managed
    _SERVICE_NAME: santander-frontend
    _TRIGGER_ID: acdb1bec-65fb-4f85-828a-a2fb36729a7c
  tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - santander-frontend
createTime: '2024-02-11T21:54:59.304441424Z'
description: Build and deploy to Cloud Run service santander-frontend on push to "^release\/.*"
github:
  name: santander-mlops
  owner: shaleenb
  push:
    tag: v.*
id: acdb1bec-65fb-4f85-828a-a2fb36729a7c
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: rmgpgab-santander-frontend-asia-south2-shaleenb-santander-mleci
resourceName: projects/santander-mlops/locations/global/triggers/acdb1bec-65fb-4f85-828a-a2fb36729a7c
serviceAccount: projects/-/serviceAccounts/311376739431-compute@developer.gserviceaccount.com
substitutions:
  _AR_HOSTNAME: asia-south2-docker.pkg.dev
  _DEPLOY_REGION: asia-south2
  _PLATFORM: managed
  _SERVICE_NAME: santander-frontend
  _TRIGGER_ID: acdb1bec-65fb-4f85-828a-a2fb36729a7c
tags:
- gcp-cloud-build-deploy-cloud-run
- gcp-cloud-build-deploy-cloud-run-managed
- santander-frontend
