build:
  images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  options:
    logging: CLOUD_LOGGING_ONLY
    substitutionOption: ALLOW_LOOSE
  steps:
  - args:
    - build
    - --no-cache
    - -t
    - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    - .
    - -f
    - backend.dockerfile
    id: Build
    name: gcr.io/cloud-builders/docker
  - args:
    - push
    - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
    name: gcr.io/cloud-builders/docker
  - args:
    - run
    - services
    - update
    - $_SERVICE_NAME
    - --platform=managed
    - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
    - --region=$_DEPLOY_REGION
    - --quiet
    entrypoint: gcloud
    id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  substitutions:
    _AR_HOSTNAME: asia-south2-docker.pkg.dev
    _DEPLOY_REGION: asia-south2
    _PLATFORM: managed
    _SERVICE_NAME: santander-backend
    _TRIGGER_ID: 6e43f0af-e3ba-4d48-82c4-3b47ae8776d7
  tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - santander-backend
createTime: '2024-02-11T21:55:59.021823252Z'
description: Build and deploy to Cloud Run service santander-backend on creation of
  new tag
github:
  name: santander-mlops
  owner: shaleenb
  push:
    tag: v.*
id: 6e43f0af-e3ba-4d48-82c4-3b47ae8776d7
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: rmgpgab-santander-backend-asia-south2-shaleenb-santander-mlotzl
resourceName: projects/santander-mlops/locations/global/triggers/6e43f0af-e3ba-4d48-82c4-3b47ae8776d7
serviceAccount: projects/-/serviceAccounts/311376739431-compute@developer.gserviceaccount.com
substitutions:
  _AR_HOSTNAME: asia-south2-docker.pkg.dev
  _DEPLOY_REGION: asia-south2
  _PLATFORM: managed
  _SERVICE_NAME: santander-backend
  _TRIGGER_ID: 6e43f0af-e3ba-4d48-82c4-3b47ae8776d7
tags:
- gcp-cloud-build-deploy-cloud-run
- gcp-cloud-build-deploy-cloud-run-managed
- santander-backend
