name: Backend CI

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]
  pull_request:
    branches: ["main"]
    paths: ["backend/**"]
  workflow_dispatch:


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file backend.dockerfile --tag mlops-backend
      - name: Run Container & Perform Tests
        run: |
          docker run --name mlops-tests mlops-backend /bin/bash -c "\
          pip install pytest pytest-cov pytest-html httpx bandit && \
          pytest --cov=. --cov-report=html:coverage.html --html=pytest.html && \
          bandit -r --exclude tests . -f html -o bandit.html"
      - name: Copy Reports from Container
        run: |
          docker cp mlops-tests:/app/pytest.html pytest.html
          docker cp mlops-tests:/app/assets assets
          docker cp mlops-tests:/app/coverage.html coverage.html
          docker cp mlops-tests:/app/bandit.html bandit.html
      - name: Upload Testing Reports as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Testing Reports
          path: |
            ./pytest.html
            ./assets
            ./coverage.html
            ./bandit.html
