name: Frontend Docker Image CI

on:
  push:
    branches: ["main"]
    paths: ["frontend/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**"]
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker Tag"
        required: false
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          DOCKER_TAG=${{ inputs.docker_tag }}
          if [ -z "$DOCKER_TAG" ]; then
            DOCKER_TAG=$(date +%s)
          fi
          docker build . --file frontend.dockerfile --tag shabenga/santander-mlops-frontend:$DOCKER_TAG
